#!/bin/bash
# 19/5/26

# script to perform read quality checking

#SBATCH --job-name=readQC
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=30g
#SBATCH --time=4:00:00

# set QC run (because we will run it again after trimming)
# so the second time we can just change this to 2
#run=1
#run=2
#run=3
#run=4

# setup env
module load fastqc-uoneasy/0.12.1-Java-11
#mkdir -p /gpfs01/home/mbzlld/data/tradis/fastqc_$run
cd /gpfs01/home/mbzlld/data/tradis


# run fastqc on all fastq files
# for the first run
#fastqc rawdata/*/*_1.fq.gz -o fastqc_$run -t 32
# for the second run
#fastqc fastp_trimmed_fastqs/*.fq.gz -o fastqc_$run -t 32
# for the third run and the 4th
#fastqc cutadapt_trimmed_fastqs/*.fq.gz -o fastqc_$run -t 32
# on the reads trimmed with fastqc then cutadapt
fastqc trimmed_fastqs/2_cutadapt/*.fq.gz -o trimmed_fastqs/2_cutadapt/reports/fastqc -t 32


# run multiqc to merge the individual reports generated by fastqc
multiqc trimmed_fastqs/2_cutadapt/reports/fastqc -o trimmed_fastqs/2_cutadapt/reports/multiqc

# unload software
module unload fastqc-uoneasy/0.12.1-Java-11

